// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// baatz_fast_segmenter_cpp
Rcpp::IntegerVector baatz_fast_segmenter_cpp(const arma::mat& image, int nrows, int ncols, double scale_param, double color_weight, double compactness_weight, Nullable<NumericVector> band_weights, bool verbose);
RcppExport SEXP _rsegm_baatz_fast_segmenter_cpp(SEXP imageSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP scale_paramSEXP, SEXP color_weightSEXP, SEXP compactness_weightSEXP, SEXP band_weightsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< double >::type scale_param(scale_paramSEXP);
    Rcpp::traits::input_parameter< double >::type color_weight(color_weightSEXP);
    Rcpp::traits::input_parameter< double >::type compactness_weight(compactness_weightSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type band_weights(band_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(baatz_fast_segmenter_cpp(image, nrows, ncols, scale_param, color_weight, compactness_weight, band_weights, verbose));
    return rcpp_result_gen;
END_RCPP
}
// baatz_segmenter_cpp
Rcpp::IntegerVector baatz_segmenter_cpp(const arma::mat& image, int nrows, int ncols, double scale_param, double color_weight, double compactness_weight, Rcpp::Nullable<Rcpp::NumericVector> band_weights);
RcppExport SEXP _rsegm_baatz_segmenter_cpp(SEXP imageSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP scale_paramSEXP, SEXP color_weightSEXP, SEXP compactness_weightSEXP, SEXP band_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< double >::type scale_param(scale_paramSEXP);
    Rcpp::traits::input_parameter< double >::type color_weight(color_weightSEXP);
    Rcpp::traits::input_parameter< double >::type compactness_weight(compactness_weightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type band_weights(band_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(baatz_segmenter_cpp(image, nrows, ncols, scale_param, color_weight, compactness_weight, band_weights));
    return rcpp_result_gen;
END_RCPP
}
// fh_meanshift_segmenter_cpp
Rcpp::IntegerVector fh_meanshift_segmenter_cpp(NumericVector img_d, int nrow, int ncol, int nb, double fh_k, int fh_min_size, bool eight, int ms_dim, double ms_ranger, double ms_hs, int ms_max_iter, double ms_eps, double mode_merge, int final_min_size, bool keep_invalid_na);
RcppExport SEXP _rsegm_fh_meanshift_segmenter_cpp(SEXP img_dSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP nbSEXP, SEXP fh_kSEXP, SEXP fh_min_sizeSEXP, SEXP eightSEXP, SEXP ms_dimSEXP, SEXP ms_rangerSEXP, SEXP ms_hsSEXP, SEXP ms_max_iterSEXP, SEXP ms_epsSEXP, SEXP mode_mergeSEXP, SEXP final_min_sizeSEXP, SEXP keep_invalid_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img_d(img_dSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type fh_k(fh_kSEXP);
    Rcpp::traits::input_parameter< int >::type fh_min_size(fh_min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type eight(eightSEXP);
    Rcpp::traits::input_parameter< int >::type ms_dim(ms_dimSEXP);
    Rcpp::traits::input_parameter< double >::type ms_ranger(ms_rangerSEXP);
    Rcpp::traits::input_parameter< double >::type ms_hs(ms_hsSEXP);
    Rcpp::traits::input_parameter< int >::type ms_max_iter(ms_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type ms_eps(ms_epsSEXP);
    Rcpp::traits::input_parameter< double >::type mode_merge(mode_mergeSEXP);
    Rcpp::traits::input_parameter< int >::type final_min_size(final_min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_invalid_na(keep_invalid_naSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_meanshift_segmenter_cpp(img_d, nrow, ncol, nb, fh_k, fh_min_size, eight, ms_dim, ms_ranger, ms_hs, ms_max_iter, ms_eps, mode_merge, final_min_size, keep_invalid_na));
    return rcpp_result_gen;
END_RCPP
}
// fh_segmenter_cpp
IntegerVector fh_segmenter_cpp(NumericVector img, int nrow, int ncol, int nb, double k, int min_size, bool eight);
RcppExport SEXP _rsegm_fh_segmenter_cpp(SEXP imgSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP nbSEXP, SEXP kSEXP, SEXP min_sizeSEXP, SEXP eightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type eight(eightSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_segmenter_cpp(img, nrow, ncol, nb, k, min_size, eight));
    return rcpp_result_gen;
END_RCPP
}
// meanshift_segmenter_cpp
Rcpp::List meanshift_segmenter_cpp(NumericVector img_d, int nrow, int ncol, int nb, int spatialr, double ranger, int max_iter, double eps, double merge_thr, int min_size, bool eight);
RcppExport SEXP _rsegm_meanshift_segmenter_cpp(SEXP img_dSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP nbSEXP, SEXP spatialrSEXP, SEXP rangerSEXP, SEXP max_iterSEXP, SEXP epsSEXP, SEXP merge_thrSEXP, SEXP min_sizeSEXP, SEXP eightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img_d(img_dSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type spatialr(spatialrSEXP);
    Rcpp::traits::input_parameter< double >::type ranger(rangerSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type merge_thr(merge_thrSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type eight(eightSEXP);
    rcpp_result_gen = Rcpp::wrap(meanshift_segmenter_cpp(img_d, nrow, ncol, nb, spatialr, ranger, max_iter, eps, merge_thr, min_size, eight));
    return rcpp_result_gen;
END_RCPP
}
// seeds_segmenter_cpp
IntegerVector seeds_segmenter_cpp(const NumericMatrix& img, int nrow, int ncol, int step, int nbins, IntegerVector block_sizes, int iters_per_level, int boundary_samples, double alpha, bool verbose);
RcppExport SEXP _rsegm_seeds_segmenter_cpp(SEXP imgSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP stepSEXP, SEXP nbinsSEXP, SEXP block_sizesSEXP, SEXP iters_per_levelSEXP, SEXP boundary_samplesSEXP, SEXP alphaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type nbins(nbinsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type block_sizes(block_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type iters_per_level(iters_per_levelSEXP);
    Rcpp::traits::input_parameter< int >::type boundary_samples(boundary_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(seeds_segmenter_cpp(img, nrow, ncol, step, nbins, block_sizes, iters_per_level, boundary_samples, alpha, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsegm_baatz_fast_segmenter_cpp", (DL_FUNC) &_rsegm_baatz_fast_segmenter_cpp, 8},
    {"_rsegm_baatz_segmenter_cpp", (DL_FUNC) &_rsegm_baatz_segmenter_cpp, 7},
    {"_rsegm_fh_meanshift_segmenter_cpp", (DL_FUNC) &_rsegm_fh_meanshift_segmenter_cpp, 15},
    {"_rsegm_fh_segmenter_cpp", (DL_FUNC) &_rsegm_fh_segmenter_cpp, 7},
    {"_rsegm_meanshift_segmenter_cpp", (DL_FUNC) &_rsegm_meanshift_segmenter_cpp, 11},
    {"_rsegm_seeds_segmenter_cpp", (DL_FUNC) &_rsegm_seeds_segmenter_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsegm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
