// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fh_meanshift_segmenter_cpp
Rcpp::IntegerVector fh_meanshift_segmenter_cpp(NumericVector img_d, int nrow, int ncol, int nb, double fh_k, int fh_min_size, bool eight, int ms_dim, double ms_ranger, double ms_hs, int ms_max_iter, double ms_eps, double mode_merge, int final_min_size, bool keep_invalid_na);
RcppExport SEXP _rsegm_fh_meanshift_segmenter_cpp(SEXP img_dSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP nbSEXP, SEXP fh_kSEXP, SEXP fh_min_sizeSEXP, SEXP eightSEXP, SEXP ms_dimSEXP, SEXP ms_rangerSEXP, SEXP ms_hsSEXP, SEXP ms_max_iterSEXP, SEXP ms_epsSEXP, SEXP mode_mergeSEXP, SEXP final_min_sizeSEXP, SEXP keep_invalid_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img_d(img_dSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type fh_k(fh_kSEXP);
    Rcpp::traits::input_parameter< int >::type fh_min_size(fh_min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type eight(eightSEXP);
    Rcpp::traits::input_parameter< int >::type ms_dim(ms_dimSEXP);
    Rcpp::traits::input_parameter< double >::type ms_ranger(ms_rangerSEXP);
    Rcpp::traits::input_parameter< double >::type ms_hs(ms_hsSEXP);
    Rcpp::traits::input_parameter< int >::type ms_max_iter(ms_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type ms_eps(ms_epsSEXP);
    Rcpp::traits::input_parameter< double >::type mode_merge(mode_mergeSEXP);
    Rcpp::traits::input_parameter< int >::type final_min_size(final_min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_invalid_na(keep_invalid_naSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_meanshift_segmenter_cpp(img_d, nrow, ncol, nb, fh_k, fh_min_size, eight, ms_dim, ms_ranger, ms_hs, ms_max_iter, ms_eps, mode_merge, final_min_size, keep_invalid_na));
    return rcpp_result_gen;
END_RCPP
}
// fh_segmenter_cpp
IntegerVector fh_segmenter_cpp(NumericVector img, int nrow, int ncol, int nb, double k, int min_size, bool eight);
RcppExport SEXP _rsegm_fh_segmenter_cpp(SEXP imgSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP nbSEXP, SEXP kSEXP, SEXP min_sizeSEXP, SEXP eightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type eight(eightSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_segmenter_cpp(img, nrow, ncol, nb, k, min_size, eight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsegm_fh_meanshift_segmenter_cpp", (DL_FUNC) &_rsegm_fh_meanshift_segmenter_cpp, 15},
    {"_rsegm_fh_segmenter_cpp", (DL_FUNC) &_rsegm_fh_segmenter_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsegm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
