# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

baatz_fast_segmenter_cpp <- function(image, nrows, ncols, scale_param, color_weight = 0.9, compactness_weight = 0.5, band_weights = NULL, verbose = FALSE) {
    .Call(`_rsegm_baatz_fast_segmenter_cpp`, image, nrows, ncols, scale_param, color_weight, compactness_weight, band_weights, verbose)
}

baatz_segmenter_cpp <- function(image, nrows, ncols, scale_param, color_weight = 0.9, compactness_weight = 0.5, band_weights = NULL) {
    .Call(`_rsegm_baatz_segmenter_cpp`, image, nrows, ncols, scale_param, color_weight, compactness_weight, band_weights)
}

fh_meanshift_segmenter_cpp <- function(img_d, nrow, ncol, nb, fh_k = 0.5, fh_min_size = 20L, eight = TRUE, ms_dim = 0L, ms_ranger = 0.2, ms_hs = 10.0, ms_max_iter = 10L, ms_eps = 1e-3, mode_merge = 0.6, final_min_size = 50L, keep_invalid_na = TRUE) {
    .Call(`_rsegm_fh_meanshift_segmenter_cpp`, img_d, nrow, ncol, nb, fh_k, fh_min_size, eight, ms_dim, ms_ranger, ms_hs, ms_max_iter, ms_eps, mode_merge, final_min_size, keep_invalid_na)
}

fh_segmenter_cpp <- function(img, nrow, ncol, nb, k = 0.8, min_size = 30L, eight = TRUE) {
    .Call(`_rsegm_fh_segmenter_cpp`, img, nrow, ncol, nb, k, min_size, eight)
}

meanshift_segmenter_cpp <- function(img_d, nrow, ncol, nb, spatialr = 5L, ranger = 1.0, max_iter = 10L, eps = 1e-3, merge_thr = NA_real_, min_size = 30L, eight = TRUE) {
    .Call(`_rsegm_meanshift_segmenter_cpp`, img_d, nrow, ncol, nb, spatialr, ranger, max_iter, eps, merge_thr, min_size, eight)
}

seeds_segmenter_cpp <- function(img, nrow, ncol, step, nbins = 16L, block_sizes = as.integer( c(8,4,2,1)), iters_per_level = 5L, boundary_samples = 64L, alpha = 1.0, verbose = FALSE) {
    .Call(`_rsegm_seeds_segmenter_cpp`, img, nrow, ncol, step, nbins, block_sizes, iters_per_level, boundary_samples, alpha, verbose)
}

