# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fh_meanshift_cpp <- function(img_d, nrow, ncol, nb, fh_k = 0.5, fh_min_size = 20L, eight = TRUE, pca_dim = 3L, ms_ranger = 0.2, ms_hs = 10.0, ms_max_iter = 10L, ms_eps = 1e-3, mode_merge = 0.6, final_min_size = 50L, keep_invalid_na = TRUE) {
    .Call(`_rsegm_fh_meanshift_cpp`, img_d, nrow, ncol, nb, fh_k, fh_min_size, eight, pca_dim, ms_ranger, ms_hs, ms_max_iter, ms_eps, mode_merge, final_min_size, keep_invalid_na)
}

segment_fh_cpp <- function(img, nrow, ncol, nb, k = 0.8, min_size = 30L, eight = TRUE) {
    .Call(`_rsegm_segment_fh_cpp`, img, nrow, ncol, nb, k, min_size, eight)
}

